"""empty message

Revision ID: 2fa0a4097479
Revises: 
Create Date: 2024-10-17 22:02:14.428304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2fa0a4097479'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_request')
    op.drop_table('admin')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('pseudo', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('password_hash', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('salt', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('date_naissance', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('profil_photo', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('chemin_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('banned', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('date_banned', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_ban_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('count_ban', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('pseudo', name='user_pseudo_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('admin_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('pseudo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('profil_photo', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('password_hash', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('salt', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admin_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('chat_request',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pseudo', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('request_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date_rdv', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('heure', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('attachment', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('admin_choices', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_choice', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name='chat_request_admin_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='chat_request_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_request_pkey')
    )
    # ### end Alembic commands ###
